<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sliding_robot_arm_with_cam">

    <xacro:include filename="partials/materials.xacro" />
    <xacro:include filename="partials/inertial_macros.xacro" />

    <!-- world Link -->
    <!-- Gazebo implicitly fixes the world link at the origin. This is noce for models that are fixed at some origin. For models that need to move around, do NOT use this! -->
    <link name="world"></link>

    <!-- world_base_joint: world -> base_link -->
    <joint name="world_base_joint" type="fixed">
        <!-- xyz = origin offset of the joint from world link origin -->
        <origin xyz="1.5 1.0 0" rpy="0 0 0" />
        <parent link="world" />
        <child link="base_link" />
    </joint>

    <!-- base_link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="2.5 1.5 0.1" />
            </geometry>
            <!-- z=0.05 such that the box doesn't display "into the ground" -->
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <material name="green">
                <color rgba="0.2 1 0.2 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <geometry>
                <box size="2.5 1.5 0.1" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <mass value="12" />
            <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5" />
        </inertial>
    </link> 

    <!-- base_slider_joint: base_link -> slider_link -->
    <joint name="base_slider_joint" type="prismatic">
        <origin xyz="-1.25 0 0.1" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="slider_link" />
        <axis xyz="1 0 0" />
        <limit lower="0" upper="2" velocity="100" effort="100" />
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <!-- slider_link -->
    <link name="slider_link">
        <visual>
            <origin xyz="0 0 0.075" />
            <geometry>
                <box size="0.5 0.25 0.15" />
            </geometry>
            <!-- defined in partials/materials.xacro -->
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 0 0.075" />
            <geometry>
                <box size="0.5 0.25 0.15" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.5" y="0.25" z="0.15">
            <origin xyz="0 0 0.075" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- slider_arm_joint: slider_link -> arm_link -->
    <joint name="slider_arm_joint" type="revolute">
        <origin xyz="0.25 0 0.15" rpy="0 0 0"/>
        <parent link="slider_link" />
        <child link="arm_link" />
        <axis xyz="0 -1 0" />
        <limit lower="0" upper="${pi/2}" velocity="100" effort="100" />
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <!-- arm_link -->
    <xacro:property name="arm_length" value="1" />
    <xacro:property name="arm_radius" value="0.1" />
    <link name="arm_link">
        <visual>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0" />
        </xacro:inertial_cylinder>
    </link>

    <!-- arm_camera_joint -->
    <joint name="arm_camera_joint" type="fixed">
        <origin xyz="${arm_length} 0 ${arm_radius + 0.075}" rpy="0 0 0" />
        <parent link="arm_link" />
        <child link="camera_link" />
    </joint>

    <!-- camera_link -->
    <link name="camera_link">
        <visual>
            <origin xyz="-0.03 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.06 0.15 0.15" />
            </geometry>
            <material name="white" />
        </visual>
        <visual>
            <origin xyz="0.03 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="0.06" radius="0.04" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.12 0.15 0.15" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.12" y="0.15" z="0.15">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <!-- camera_optical_joint: required for using a camera in ros -->
    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.571 0 -1.571" />
        <parent link="camera_link" />
        <child link="camera_link_optical" />
    </joint>


    <!-- camera_link_optical: required for using a camera in ros -->
    <link name="camera_link_optical"></link>

    <!-- Include Gazebo tags -->
    <xacro:include filename="partials/sample_gazebo_tags.xacro" />

</robot>
